<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FNF69NB" name="Login With Email" tests="2" failures="1" timestamp="2 Dec 2016 17:40:23 GMT" time="10.505" errors="0">
  <testcase name="validateButtons" time="2.257" classname="testcases.care.CareLoginTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [4]
	at testcases.care.CareLoginTest.validateButtons(CareLoginTest.java:31)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateButtons -->
  <testcase name="signUpEmailandSelectACareGiver" time="3.549" classname="testcases.care.CareLoginTest"/>
</testsuite> <!-- Login With Email -->
